<h1>Shopping List</h1>

    <table>
        <thead>
            <th>
                <td>Id</td>
                <td>Name</td>
            </th>
        </thead>
  
        <tbody>
        <?php foreach($data as $dt): ?>
            <tr>
                <td><?=$dt['shopping_list_id']?></td>
                <td><em><?=$dt['name']?></em></td>
                <td><em><?=$dt['code']?></em></td>
                <td> <a href='/shopping/new/<?=$dt['shopping_list_id']?>'>Edit</a> | Delete</td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>